// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1beta1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/kinvolk/smi-adapter-istio/pkg/apis/smispec/v1beta1.TrafficSplit":       schema_pkg_apis_smispec_v1beta1_TrafficSplit(ref),
		"github.com/kinvolk/smi-adapter-istio/pkg/apis/smispec/v1beta1.TrafficSplitSpec":   schema_pkg_apis_smispec_v1beta1_TrafficSplitSpec(ref),
		"github.com/kinvolk/smi-adapter-istio/pkg/apis/smispec/v1beta1.TrafficSplitStatus": schema_pkg_apis_smispec_v1beta1_TrafficSplitStatus(ref),
	}
}

func schema_pkg_apis_smispec_v1beta1_TrafficSplit(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TrafficSplit is the Schema for the trafficsplits API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/kinvolk/smi-adapter-istio/pkg/apis/smispec/v1beta1.TrafficSplitSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/kinvolk/smi-adapter-istio/pkg/apis/smispec/v1beta1.TrafficSplitStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/kinvolk/smi-adapter-istio/pkg/apis/smispec/v1beta1.TrafficSplitSpec", "github.com/kinvolk/smi-adapter-istio/pkg/apis/smispec/v1beta1.TrafficSplitStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_smispec_v1beta1_TrafficSplitSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TrafficSplitSpec defines the desired state of TrafficSplit",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_smispec_v1beta1_TrafficSplitStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TrafficSplitStatus defines the observed state of TrafficSplit",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
